@hostname = http://localhost:3000

GET {{hostname}}
###
POST {{hostname}}/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}
###
POST {{hostname}}/signup
Content-Type: application/json

{
  "username": "admin",
  "password": "password",
  "confirmPassword": "password",
  "deleteAfter": true
}
###
GET {{hostname}}/user/1
###
POST {{hostname}}/account
Content-Type: application/json
###
GET {{hostname}}/error-route
# for the error handler
###
GET {{hostname}}/notfound-route
# for the catchall

